/** @type {import('tailwindcss').Config} */

module.exports = {
  content: ["./{app,components}/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        sans: ["ZwiftSprint-Regular", "Helvetica", "Arial", "sans-serif"],
      },
      fontSize: {
        md: "1.125rem",
      },
      colors: {
        default: {
          DEFAULT: "rgb(var(--color-default) / <alpha-value>)",
          50: "rgb(var(--color-default-50) / <alpha-value>)",
          100: "rgb(var(--color-default-100) / <alpha-value>)",
          200: "rgb(var(--color-default-200) / <alpha-value>)",
          300: "rgb(var(--color-default-300) / <alpha-value>)",
          400: "rgb(var(--color-default-400) / <alpha-value>)",
          500: "rgb(var(--color-default-500) / <alpha-value>)",
          600: "rgb(var(--color-default-600) / <alpha-value>)",
          700: "rgb(var(--color-default-700) / <alpha-value>)",
          800: "rgb(var(--color-default-800) / <alpha-value>)",
          900: "rgb(var(--color-default-900) / <alpha-value>)",
          950: "rgb(var(--color-default-950) / <alpha-value>)",
        },
        primary: {
          DEFAULT: "rgb(var(--color-primary) / <alpha-value>)",
          50: "rgb(var(--color-primary-50) / <alpha-value>)",
          100: "rgb(var(--color-primary-100) / <alpha-value>)",
          200: "rgb(var(--color-primary-200) / <alpha-value>)",
          300: "rgb(var(--color-primary-300) / <alpha-value>)",
          400: "rgb(var(--color-primary-400) / <alpha-value>)",
          500: "rgb(var(--color-primary-500) / <alpha-value>)",
          600: "rgb(var(--color-primary-600) / <alpha-value>)",
          700: "rgb(var(--color-primary-700) / <alpha-value>)",
          800: "rgb(var(--color-primary-800) / <alpha-value>)",
          900: "rgb(var(--color-primary-900) / <alpha-value>)",
          950: "rgb(var(--color-primary-950) / <alpha-value>)",
        },
        secondary: {
          DEFAULT: "rgb(var(--color-secondary) / <alpha-value>)",
          50: "rgb(var(--color-secondary-50) / <alpha-value>)",
          100: "rgb(var(--color-secondary-100) / <alpha-value>)",
          200: "rgb(var(--color-secondary-200) / <alpha-value>)",
          300: "rgb(var(--color-secondary-300) / <alpha-value>)",
          400: "rgb(var(--color-secondary-400) / <alpha-value>)",
          500: "rgb(var(--color-secondary-500) / <alpha-value>)",
          600: "rgb(var(--color-secondary-600) / <alpha-value>)",
          700: "rgb(var(--color-secondary-700) / <alpha-value>)",
          800: "rgb(var(--color-secondary-800) / <alpha-value>)",
          900: "rgb(var(--color-secondary-900) / <alpha-value>)",
          950: "rgb(var(--color-secondary-950) / <alpha-value>)",
        },
        background: "rgb(var(--color-background) / <alpha-value>)",
        foreground: "rgb(var(--color-foreground) / <alpha-value>)",
        red: "rgb(var(--color-red) / <alpha-value>)",
        green: "rgb(var(--color-green) / <alpha-value>)",
        blue: "rgb(var(--color-blue) / <alpha-value>)",
        yellow: "rgb(var(--color-yellow) / <alpha-value>)",
        purple: "rgb(var(--color-purple) / <alpha-value>)",
      },
    },
  },
  plugins: [],
};
