export type Rider = {
  name: string;
  friend: number;
  ftp: string;
  zwid: number;
  s: string;
  pt: string;
  tid: string;
  topen: string;
  tname: string;
  tc: string;
  tbc: string;
  tbd: string;
  flag: string;
  w: string;
  age: string;
  height: [number, number];
  gender: string;
  zada: number;
  events: string;
  div: number;
  divw: number;
  rank: string;
  skill: number;
  skill_race: number;
  skill_seg: number;
  skill_power: number;
  skill_pos: number;
  reg: number;
  eff: string;
  fl: string;
  label: number;
  watts: unknown[];
  msec: unknown[];
  cp_1200_wkg: [number, string, string] | undefined;
  cp_300_wkg: [number, string, string] | undefined;
  cp_60_wkg: [number, string, string] | undefined;
  cp_1200_watts: [number, string, string] | undefined;
  cp_300_watts: [number, string, string] | undefined;
  cp_60_watts: [number, string, string] | undefined;
  cp_15_wkg: [number, string, string] | undefined;
  cp_15_watts: [number, string, string] | undefined;
  lead: number;
  sweep: number;
  wrg_cat: number;
  weight: [string, number];
};
