name: Coverage
on:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"
          cache: "npm"

      - uses: ArtiomTr/jest-coverage-report-action@v2
