name: Coverage
on:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.38

      - name: Install dependencies
        run: bun install

      - uses: ArtiomTr/jest-coverage-report-action@v2
